-- De Stampertjes v2.22 — Het Kasteel Onthoudt
begin;

create table if not exists public.game_metrics (
  id bigint generated by default as identity primary key,
  device_id uuid not null,
  metric text not null,
  value numeric not null default 1,
  extra jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists game_metrics_device_metric_idx
  on public.game_metrics(device_id,metric,created_at desc);

alter table public.game_metrics enable row level security;

-- Geen directe publieke tabeltoegang: de game schrijft uitsluitend via RPC.
revoke all on public.game_metrics from anon, authenticated;

create or replace function public.record_game_metric(
  p_device_id uuid,
  p_metric text,
  p_value numeric default 1,
  p_extra jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  allowed constant text[] := array[
    'session_seconds','level_start','level_complete','stamp','hole_created',
    'apple_defeated','apple_in_hole','bonus_spawn','bonus_collect',
    'teddy_spawn','teddy_encounter','teddy_missed','combo_best'
  ];
begin
  if p_device_id is null or p_metric is null or not (p_metric = any(allowed)) then
    return;
  end if;
  insert into public.game_metrics(device_id,metric,value,extra)
  values(p_device_id,p_metric,coalesce(p_value,0),coalesce(p_extra,'{}'::jsonb));
end;
$$;

revoke all on function public.record_game_metric(uuid,text,numeric,jsonb) from public;
grant execute on function public.record_game_metric(uuid,text,numeric,jsonb) to anon, authenticated;

-- Grove locatie is optioneel en bewust beperkt tot land/regio; geen GPS/IP-history.
alter table public.player_stats add column if not exists country_code text;
alter table public.player_stats add column if not exists region_name text;
alter table public.player_stats add column if not exists first_played_at timestamptz default now();
alter table public.player_stats add column if not exists last_played_at timestamptz default now();

create or replace function public.get_v222_analytics()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
select jsonb_build_object(
  'total_metric_events',(select count(*) from public.game_metrics),
  'total_play_seconds',coalesce((select sum(value) from public.game_metrics where metric='session_seconds'),0),
  'level_starts',coalesce((select jsonb_object_agg(level,cnt) from (
      select coalesce(extra->>'level','?') level,count(*) cnt
      from public.game_metrics where metric='level_start'
      group by 1
  ) q),'{}'::jsonb),
  'level_completions',coalesce((select jsonb_object_agg(level,cnt) from (
      select coalesce(extra->>'level','?') level,count(*) cnt
      from public.game_metrics where metric='level_complete'
      group by 1
  ) q),'{}'::jsonb),
  'countries',coalesce((select jsonb_object_agg(country_code,cnt) from (
      select country_code,count(*) cnt from public.player_stats
      where country_code is not null group by country_code
  ) q),'{}'::jsonb)
);
$$;

revoke all on function public.get_v222_analytics() from public;
grant execute on function public.get_v222_analytics() to anon, authenticated;

commit;
